# Generated by Django 6.0.2 on 2026-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students')),
            ],
            options={
                'db_table': 'pages_student',
            },
        ),
    ]
