# Generated by Django 6.0.2 on 2026-09-30 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram')], max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pages_socialmediaconnections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.RemoveField(
            model_name='socialmediametric',
            name='engagement',
        ),
        migrations.AddField(
            model_name='socialmediametric',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediametric',
            name='comments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediametric',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediametric',
            name='shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediametric',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram')], max_length=20),
        ),
    ]
