# Generated by Django 6.0.2 on 2026-09-30 07:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshop_created_by_alter_workshop_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('origin_name', models.CharField(max_length=120)),
                ('origin_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('origin_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('destination_name', models.CharField(max_length=120)),
                ('destination_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('destination_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('contents_summary', models.TextField()),
                ('impact_summary', models.TextField(blank=True)),
                ('partner_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='planned', max_length=12)),
                ('status_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-status_date', '-pk'),
            },
        ),
    ]
